"""Список ссылок на фиды."""
FEEDS = [
    'https://feeds-mic.s1.citilink.ru/context/context_msk_cl.xml',
    'https://feeds-mic.s1.citilink.ru/context/context_spb_cl.xml',
    'https://feeds-mic.s1.citilink.ru/context/context_vrzh_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_nnov_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_perm_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_ufa_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_kzn_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_smr_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_srt_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_vlg_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_krd_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_rnd_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_omk_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_krasn_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_tom_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_ekat_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_chlb_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_nvs_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_yar_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/context/context_stav_cl.xml',
    # 'https://feeds-mic.s1.citilink.ru/ya_search/ya_search_msk_cl.xml',
]
